logLevel = "WARN"
defaultEntryPoints = ["https","http"]

# [api]

[docker]
domain = "dacio.app"
exposedByDefault = false
watch = true
network = "web"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"

  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "dacioromero@gmail.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"

  [acme.dnsChallenge]
  provider = "digitalocean"

  [[acme.domains]]
    main = "*.dacio.app"
    sans = ["dacio.app"]
